name       : gnome-mpv
version    : '0.10'
release    : 10
source     :
    - https://github.com/gnome-mpv/gnome-mpv/releases/download/v0.10/gnome-mpv-0.10.tar.xz : 92d967bbbbfabdfa3ab1f19be625f684959513890b2035ca6102292392fbf183
license    : GPL-3.0
component  : multimedia.video
summary    : GNOME frontend for MPV
description: |
    GNOME frontend for MPV
builddeps  :
    - autoconf-archive
    - pkgconfig(mpv)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(libass)
    - pkgconfig(appstream-glib)
setup      : |
    autoreconf -sfi
    intltoolize -c --automake
    %configure --enable-debug
build      : |
    %make
install    : |
    %make_install
