name       : gnome-mpv
version    : '0.13'
release    : 23
source     :
    - https://github.com/gnome-mpv/gnome-mpv/releases/download/v0.13/gnome-mpv-0.13.tar.xz : c5a288c7095ccbe520b3ba419856e29981f4a2d204e7cfa264ee69edab2724f1
license    : GPL-3.0
component  : multimedia.video
summary    : GNOME frontend for MPV
description: |
    GNOME frontend for MPV
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mpv)
rundeps    :
    - youtube-dl
setup      : |
    %patch -p1 < $pkgfiles/update-appdata-and-add-missing-meson-build-file.patch
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install

