name       : gnome-mpv
version    : 0.6
release    : 6
source     :
    - https://github.com/gnome-mpv/gnome-mpv/archive/v0.6.tar.gz : e1544c5b2055cc0a92af625b87f53422e05dbe39043c5d5b3d6db1a75e3435c0
license    : GPL-3.0
summary    : GNOME frontend for MPV
description: |
    GNOME frontend for MPV
builddeps  :
    - autoconf-archive
    - pkgconfig(mpv)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(libass)
setup      : |
    autoreconf -sfi
    intltoolize -c --automake
    %configure --enable-debug
build      : |
    %make
install    : |
    %make_install
