name       : gnome-mpv
version    : '0.14'
release    : 25
source     :
    - https://github.com/gnome-mpv/gnome-mpv/releases/download/v0.14/gnome-mpv-0.14.tar.xz : 23c9bde58da8ccf0e36c30b7d94d504aca9502288e4bb8ad5425022c4be3720e
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : GNOME frontend for MPV
description: |
    GNOME frontend for MPV
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mpv)
rundeps    :
    - youtube-dl
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
