name       : celluloid
version    : '0.24'
release    : 33
source     :
    - https://github.com/celluloid-player/celluloid/archive/refs/tags/v0.24.tar.gz : 725afebadef7b37b2e3452c00575cee50aee0a2e7dceb848112e06095af3977e
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : A simple GTK+ frontend for MPV
description: |
    Celluloid (formerly GNOME MPV) is a simple GTK+ frontend for mpv. Celluloid interacts with mpv via the client API exported by libmpv, allowing access to mpv's powerful playback capabilities.
replaces   :
    - gnome-mpv
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(libadwaita-1)
    - pkgconfig(mpv)
rundeps    :
    - yt-dlp
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-MPV-hwdec-by-default.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
