name       : gnome-mpv
version    : 0.5
release    : 4
source     :
    - https://github.com/gnome-mpv/gnome-mpv/archive/v0.5.tar.gz : 56064c16fb9a8b4e79cdd338800dd989588bed11574e4993a36308707e304cf3
license    : GPLv3
summary    : GNOME frontend for MPV
description: |
    GNOME frontend for MPV
builddeps  :
    - pkgconfig(mpv)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(libass)
setup      : |
    autoreconf -sfi
    intltoolize -c --automake
    %configure --enable-debug
build      : |
    %make
install    : |
    %make_install
