name       : gnome-mpv
version    : '0.15'
release    : 27
source     :
    - https://github.com/gnome-mpv/gnome-mpv/releases/download/v0.15/gnome-mpv-0.15.tar.xz : e4e08ad9de7c883e583c56f440bc7e6f584e5f1b19e1bd008d01f616e75287f8
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : GNOME frontend for MPV
description: |
    GNOME frontend for MPV
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mpv)
rundeps    :
    - youtube-dl
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
