name       : celluloid
version    : '0.25'
release    : 36
source     :
    - https://github.com/celluloid-player/celluloid/archive/refs/tags/v0.25.tar.gz : 03338b311725e2b680e81407eef6471534a5600c73d93a22315a479b5529119f
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : A simple GTK+ frontend for MPV
description: |
    Celluloid (formerly GNOME MPV) is a simple GTK+ frontend for mpv. Celluloid interacts with mpv via the client API exported by libmpv, allowing access to mpv's powerful playback capabilities.
replaces   :
    - gnome-mpv
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(epoxy)
    - pkgconfig(libadwaita-1)
    - pkgconfig(mpv)
    - desktop-file-utils
setup      : |
    %patch -p1 < $pkgfiles/0001-Enable-MPV-hwdec-by-default.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
