name       : gnome-mpv
version    : '0.16'
release    : 30
source     :
    - https://github.com/gnome-mpv/gnome-mpv/releases/download/v0.16/gnome-mpv-0.16.tar.xz : 22cd8a9257ea57449f3120993e668d11e5e3be31444c6e63b8b25ccce0feed4b
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : GNOME frontend for MPV
description: |
    GNOME frontend for MPV
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mpv)
rundeps    :
    - youtube-dl
setup      : |
    %apply_patches
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
