name       : gnome-mpv
version    : 0.7
release    : 9
source     :
    - https://github.com/gnome-mpv/gnome-mpv/archive/v0.7.tar.gz : 94b9d9ff0afe4375d0fe6f53df6069de193d009488988014b0e30e23edad49a5
license    : GPL-3.0
component  : multimedia.video
summary    : GNOME frontend for MPV
description: |
    GNOME frontend for MPV
builddeps  :
    - autoconf-archive
    - pkgconfig(mpv)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(libass)
    - pkgconfig(appstream-glib)
setup      : |
    autoreconf -sfi
    intltoolize -c --automake
    %configure --enable-debug
build      : |
    %make
install    : |
    %make_install
