name       : gnome-mpv
version    : '0.12'
release    : 19
source     :
    - https://github.com/gnome-mpv/gnome-mpv/releases/download/v0.12/gnome-mpv-0.12.tar.xz : 6c121261a1ea7e8065379c5355c2b2061eb4abbff0c8121ada211d4777fa9635
license    : GPL-3.0
component  : multimedia.video
summary    : GNOME frontend for MPV
description: |
    GNOME frontend for MPV
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(mpv)
rundeps    :
    - youtube-dl
setup      : |
    %patch -p1 < $pkgfiles/bump-meson-version.patch
    %configure
build      : |
    %make
install    : |
    %make_install
