name       : gnome-mpv
version    : 0.11
release    : 13
source     :
    - https://github.com/gnome-mpv/gnome-mpv/releases/download/v0.11/gnome-mpv-0.11.tar.xz : ffb9a1b36504cc8b659c69493c913709451349947f936f41158ee7d5f5adc3c2
license    : GPL-3.0
component  : multimedia.video
summary    : GNOME frontend for MPV
description: |
    GNOME frontend for MPV
builddeps  :
    - pkgconfig(appstream-glib)
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libass)
    - pkgconfig(mpv)
    - autoconf-archive
setup      : |
    autoreconf -sfi
    intltoolize -c --automake
    %configure --enable-debug
build      : |
    %make
install    : |
    %make_install
